POE breaks caja.result. Does it break debugmode?


Original issue 348 created by erights on 2008-06-01T02:44:32.000Z:
<script type="text/javascript">
caja.result("foo");
</script>
used to work, but no longer does. The r1541 testbed applet defines
caja.result by:
caja.result = ___.simpleFunc(function (o) {
...
with the global caja object. Within the applet (eval.html in the current
version), caja.result is no longer callable. I suspect that's because
eval.html is depending on the isJSONContainer-ness of the global "caja"
object to provide access, whereas caja.js is explicitly calling allowCall
on it. Either would work on the global caja object itself. But POE instead
provides the plugin with a beget of the caja object. This per-plugin caja
object mistakenly passes isJSONContainer (as explained elsewhere). But
"result" isn't an own property of it, so unless it's globally whitelisted,
it's not accessible.
AFAICT, this has no security risk and is only a minor annoyance, so I'm
giving it a low priority. However, I wonder if there might be similar bad
interactions between POE and debugmode, so I am flagging this as
security-relevant.
