Creating a Rietveld issue is less atomic than it should be


Original issue 1871 created by kpreid@google.com on 2013-11-07T22:33:19.000Z:
What steps will reproduce the problem?

Run 'myvn mail' or 'myvn snapshot' to create an issue.
Have a network or server failure occur while uploading changes/base files.

What is the expected output? What do you see instead?
The issue will have been created, and its URL printed, but the issue ID is not inserted in the .appspot-change file. This means that retrying will result in creating a duplicate issue.
appspot.py should write the .appspot-change file as soon as the Rietveld server gives us the change ID, not after doing other operations that might fail.
