failure_forward should results in a 401 response on auth failure


When using the form_login with failure_forward: true, the response in a case of an authentication failure should have a 401 status code (as use_forward: true results in a 401 response when accessing a restricted area)
suppose this firwall:
    secured_area:
        pattern:    ^/protected
        context: user
        form_login:
            use_forward: true
            failure_forward: true

this is what is currently happening:

If I'm not authenticated and I go to /protected:

I'm presented with the login form
I'm still on /protected
status code is 401


I enter bad credentials and submit the login form:

I'm presented with the login form (and maybe a 'Bad credentials' message)
I'm still on /protected
status code is 200



I think 401 is the appropriated status code to return in this case because otherwise it looks like we successfully get the resource /protected
