'Custom' exception overriden when using PreAuthentication


I'm following the How to Authenticate Users with API Keys tutorial.
When I'm giving a correct API key, everything works well. On the other hand, when the API key is either incorrect or missing, the code is supposed to throw an exception (for instance BadCredentialsException in the first case). However, this exception seems to be overriden and the final request response is an AuthenticationCredentialsNotFoundException thrown by Symfony AccessListener.php.
In the logs, I read this message:
Authentication exception occurred; redirecting to authentication entry point (A Token was not found in the SecurityContext.)

This lets me think that the exception thrown in the PreAuthenticator is somehow discarded and the security mecanism only complains a step further that it can find no Token (which is indeed normal given the incorrect API key provided).
If this is the expected behaviour (which I'd found sad) there is no point in proposing a PreAuthenticator that uses exceptions in the doc...
